/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moodleapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que muestra los datos de las asignaciones.
 * @author Miranda, 
 * @author Cristina, 
 * @author Fernando, 
 * @author Guillermo.
 * 
 */
public class dlgAsignaciones extends javax.swing.JDialog {

    //Variable que crea la conexión con la BD.
    public Connection cn;
    //Variable que se comunica con la BD.
    public Statement st;
    
    /**
     * Creates new form dlgAsignaciones.
     */
    public dlgAsignaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Se centra la ventana a el medio de la pantalla
        setLocationRelativeTo(null);
        //Llama al método para conectarse a la BD.
        conexion();
        //Llama al método que muestra los datos en la tabla.
        mostrartabla();
    }
    
    /**
     * Método que realiza la conexión de la aplicación con la Base de datos.
     */
    public void conexion(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/moodle?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            st = cn.createStatement();
            JOptionPane.showMessageDialog(null, "Connected", "Moodle", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Not connected", "Moodle", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Método que obtiene los datos de la base de datos y los muestra en la tabla.
     */
    void mostrartabla(){
        //Se crea la tabla.
        DefaultTableModel modelo = new DefaultTableModel();
        //Se añaden las columnas según el tipo de dato.
        modelo.addColumn("ID");
        modelo.addColumn("ID Curso");
        modelo.addColumn("Nombre");
        modelo.addColumn("Intro");
        modelo.addColumn("No. Submissions");
        //A la tabla de la interfaz se le da el valor de la creada anteriormente.
        tablaDatos.setModel(modelo);
        
        try {
            //String que se ejecutará para obtener los datos necesarios.
            String sql = "SELECT * FROM mdl_assign";
            //Arreglo donde se guardarán los datos.
            String datos[] = new String[5];
            //Variable que obtiene y guarda el resultado donde se ejecuta el query agregado anteriormente.
            ResultSet rs  = st.executeQuery(sql);
            
            //Ciclo que recorre los valores obtenidos de la base de datos para guardarlos en el arreglo.
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(7);
                //Se agrega la fila a la tabla.
                modelo.addRow(datos);
            }
            
            //A la tabla de la interfaz se le da el valor de la creada anteriormente.
            tablaDatos.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Asignaciones disponibles");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que ayuda a regresar a la pantalla principal.
     * @param evt Evento que se lleva a cabo.
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
