/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moodleapp;

/**
 *
 * @author Miranda, 
 * @author Cristina, 
 * @author Fernando, 
 * @author Guillermo.
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        //Se centra la ventana a el medio de la pantalla
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnAsignaciones = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAsignaciones.setBackground(new java.awt.Color(255, 204, 255));
        btnAsignaciones.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnAsignaciones.setForeground(new java.awt.Color(0, 0, 0));
        btnAsignaciones.setText("Asignaciones");
        btnAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionesActionPerformed(evt);
            }
        });

        btnCursos.setBackground(new java.awt.Color(204, 255, 204));
        btnCursos.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCursos.setForeground(new java.awt.Color(0, 0, 0));
        btnCursos.setText("Cursos");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnCalificaciones.setBackground(new java.awt.Color(204, 204, 255));
        btnCalificaciones.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCalificaciones.setForeground(new java.awt.Color(0, 0, 0));
        btnCalificaciones.setText("Calificaciones");
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });

        btnAlumnos.setBackground(new java.awt.Color(255, 255, 204));
        btnAlumnos.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(0, 0, 0));
        btnAlumnos.setText("Alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Moodle Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btnAlumnos))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnAsignaciones)))
                    .addComponent(btnCalificaciones))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCursos)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnAsignaciones)
                .addGap(31, 31, 31)
                .addComponent(btnCursos)
                .addGap(37, 37, 37)
                .addComponent(btnCalificaciones)
                .addGap(31, 31, 31)
                .addComponent(btnAlumnos)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método que abre la pantalla de los datos especificados.
 * Crea un objeto del dialogo y lo muestra en la pantalla.
 * @param evt Evento que se lleva a cabo.
 */
    private void btnAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionesActionPerformed
        dlgAsignaciones asig = new dlgAsignaciones(this, true);
        asig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAsignacionesActionPerformed

    /**
     * Método que abre la pantalla de los datos especificados.
     * Crea un objeto del dialogo y lo muestra en la pantalla.
     * @param evt Evento que se lleva a cabo.
     */
    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        dlgCursos cursos = new dlgCursos(this, true);
        cursos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCursosActionPerformed

    /**
     * Método que abre la pantalla de los datos especificados. 
     * Crea un objeto del dialogo y lo muestra en la pantalla.
     * @param evt Evento que se lleva a cabo.
     */
    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        dlgCalificaciones calif = new dlgCalificaciones(this, true);
        calif.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    /**
     * Método que abre la pantalla de los datos especificados.
     * Crea un objeto del dialogo y lo muestra en la pantalla.
     * @param evt Evento que se lleva a cabo.
     */
    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        dlgAlumnos alumnos = new dlgAlumnos(this, true);
        alumnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnAsignaciones;
    private javax.swing.JButton btnCalificaciones;
    private javax.swing.JButton btnCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
