/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.paneles;

import interfaces.frmAsignacion;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import objectosNegocio.Asignacion;
import objectosNegocio.ParentUser;

/**
 *
 * @author crisb
 */
public class PanelAsignacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelAsignacion
     */
    ParentUser parentUser;
    private int idAlumno, idCurso,idAsignacion;
    private Asignacion asig;
    public PanelAsignacion(ParentUser parentUser,String nombre, int idCurso, int idAsignacion, Asignacion asig) {
        initComponents();
        this.parentUser=parentUser;
        this.lblNombreAsig.setText(nombre);
        this.idAlumno=idAlumno;
        this.idCurso=idCurso;
        this.idAsignacion=idAsignacion;
        this.asig=asig;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        btnAsig = new javax.swing.JButton();
        lblNombreAsig = new javax.swing.JLabel();

        jPanel13.setBackground(new java.awt.Color(252, 189, 131));

        btnAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adelantechico.png"))); // NOI18N
        btnAsig.setBorder(null);
        btnAsig.setContentAreaFilled(false);
        btnAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsigActionPerformed(evt);
            }
        });

        lblNombreAsig.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        lblNombreAsig.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAsig.setText("Asig1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnAsig))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreAsig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsigActionPerformed
        frmAsignacion asignacion = new frmAsignacion(parentUser,idAsignacion,idCurso,asig);
        asignacion.setVisible(true);
        this.setVisible(false);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnAsigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsig;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel lblNombreAsig;
    // End of variables declaration//GEN-END:variables
}
