/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conexion.RESTConexion;
import javax.swing.JOptionPane;
import objectosNegocio.Alumno;
import objectosNegocio.DatosHijo;
import objectosNegocio.ParentUser;

/**
 *
 * @author miran
 */
public final class dlgBienvenida extends javax.swing.JDialog {

    /**
     * Creates new form dlgBienvenida
     * @param parent
     * @param modal
     */
    //RESTConexion.AlumnoResource_JerseyClient con;
    ParentUser parentUser;
    boolean fallo = false;
    public dlgBienvenida(java.awt.Frame parent, boolean modal, ParentUser parentUser) {
        super(parent, modal);
        initComponents();
        //con= new RESTConexion.AlumnoResource_JerseyClient();
        this.parentUser=parentUser;
        setLocationRelativeTo(null);
        //Aquí se van a poner los nombres
        setNombres();
    }
    
    public void setNombres(){
        
        //El papa
        lblNombrePadre.setText(parentUser.getFirstName());
        lblApellidoPadre.setText(parentUser.getLastName());
        //El alumno
        
        /*Alumno alumno= con.getAlumnoId(Alumno.class, Integer.toString(parentUser.getChildID()));
        parentUser.setChildFirstName(alumno.getNombre());
        parentUser.setChildLastName(alumno.getApellido());
        */
        try{
            DatosHijo hijo = new RESTConexion.UsuarioResource_JerseyClient().obtenerHijo(DatosHijo.class, parentUser.getToken());
            System.out.println(hijo.toString());
            lblNombreHijo.setText(hijo.getFullname());
        }
        catch(Exception e){
            lblNombreHijo.setText("[AUN NO ASIGNADO]");
            fallo = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarSesion = new javax.swing.JButton();
        lblLogo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombrePadre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreHijo = new javax.swing.JLabel();
        lblApellidoPadre = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        lblLogo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        btnIniciarSesion.setBackground(new java.awt.Color(61, 64, 64));
        btnIniciarSesion.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión");

        lblLogo1.setText("logo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 128, 18));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("padre de:");

        lblNombrePadre.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblNombrePadre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePadre.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenid@");

        lblNombreHijo.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblNombreHijo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreHijo.setText("NOMBRE");

        lblApellidoPadre.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblApellidoPadre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidoPadre.setText("APELLIDO");

        btnComenzar.setBackground(new java.awt.Color(61, 64, 64));
        btnComenzar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setText("Continuar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moodle.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hello_(yellow).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblLogo2))
                            .addComponent(lblNombreHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidoPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombrePadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))))
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombrePadre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApellidoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnComenzar)
                .addGap(67, 67, 67)
                .addComponent(lblLogo2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        if(!fallo){
            FrmPrincipal principal = new FrmPrincipal(parentUser);
            principal.setVisible(true);
        }
        else{
            FrmLogin login = new FrmLogin();
            login.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "El profesor aun no te ha asignado como padre a tu hijo. Ingrese de nuevo mas tarde.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnComenzarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidoPadre;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblNombreHijo;
    private javax.swing.JLabel lblNombrePadre;
    // End of variables declaration//GEN-END:variables
}
