/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.paneles;

import interfaces.FrmAsignaciones;
import java.awt.Dimension;
import objectosNegocio.ParentUser;

/**
 *
 * @author crisb
 */
public class PanelCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelCurso
     */
    ParentUser parentUser;
    private int idCurso;
    public PanelCurso(ParentUser parentUser,int idCurso,String nombreCurso) {
        initComponents();
        this.parentUser=parentUser;
        this.idCurso=idCurso;
        this.lblNombreCurso.setText(nombreCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCurso2 = new javax.swing.JButton();
        lblNombreCurso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 189, 131));

        btnCurso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adelante.png"))); // NOI18N
        btnCurso2.setBorder(null);
        btnCurso2.setContentAreaFilled(false);
        btnCurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurso2ActionPerformed(evt);
            }
        });

        lblNombreCurso.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        lblNombreCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCurso.setText("Ingles avanzado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurso2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCurso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurso2ActionPerformed
FrmAsignaciones asignaciones = new FrmAsignaciones(parentUser,idCurso);
        asignaciones.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCurso2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurso2;
    private javax.swing.JLabel lblNombreCurso;
    // End of variables declaration//GEN-END:variables
}
